### ISSUE TITLE
更新索引时，报错异常，而且每次都卡在那个文件夹

### ISSUE THREAD

**Issue by deYangar** [ldqk/ImageSearch#11]
**报错如下**
有关调用实时(JIT)调试而不是此对话框的详细信息，
请参见此消息的结尾。

************** 异常文本 **************
System.IO.IOException: 系统无法打开文件。 : 'X:\3D_二次元\aski\2019-10-03 21-24Pixiv4 高解像度版 HighRes'
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateRelativeDirectoryHandle(ReadOnlySpan`1 relativePath, String fullPath)
   at System.IO.Enumeration.FileSystemEnumerator`1.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToList()
   at 以图搜图.Form1.btnIndex_Click(Object sender, EventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)

**Comment by ldqk** [comment]
你可以把这个文件踢出去(手动狗头

**Comment by deYangar** [comment]
试了一下不太行，总会报错，是因为文件夹里我的图片总数太多了吗

完整报错如下

有关调用实时(JIT)调试而不是此对话框的详细信息，
请参见此消息的结尾。

************** 异常文本 **************
System.IO.IOException: 系统无法打开文件。 : 'X:\3D_二次元\【图集】ぁぁぁぁ\2018-05-19 16-3720180519配信ラクガキ'
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateRelativeDirectoryHandle(ReadOnlySpan`1 relativePath, String fullPath)
   at System.IO.Enumeration.FileSystemEnumerator`1.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToList()
   at 以图搜图.Form1.btnIndex_Click(Object sender, EventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at InvokeStub_SendOrPostCallback.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)


************** 已加载的程序集 **************
System.Private.CoreLib
    程序集版本:7.0.0.0
    Win32 版本:7.0.122.56804
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.1/System.Private.CoreLib.dll
----------------------------------------
以图搜图
    程序集版本:1.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Runtime
    程序集版本:7.0.0.0
    Win32 版本:7.0.122.56804
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.1/System.Runtime.dll
----------------------------------------
System.Diagnostics.Process
    程序集版本:7.0.0.0
    Win32 版本:7.0.122.56804
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.1/System.Diagnostics.Process.dll
----------------------------------------
System.ComponentModel.Primitives
    程序集版本:7.0.0.0
    Win32 版本:7.0.122.56804
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.1/System.ComponentModel.Primitives.dll
----------------------------------------
System.Windows.Forms
    程序集版本:7.0.0.0
    Win32 版本:7.0.122.56811
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.1/System.Windows.Forms.dll
----------------------------------------
System.Windows.Forms.Primitives
    程序集版本:7.0.0.0
    Win32 版本:7.0.122.56811
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.1/System.Windows.Forms.Primitives.dll
----------------------------------------
System.Runtime.InteropServices
    程序集版本:7.0.0.0
    Win32 版本:7.0.122.56804
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.1/System.Runtime.InteropServices.dll
----------------------------------------
System.Drawing.Primitives
    程序集版本:7.0.0.0
    Win32 版本:7.0.122.56804
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.1/System.Drawing.Primitives.dll
----------------------------------------
System.Collections.Specialized
    程序集版本:7.0.0.0
    Win32 版本:7.0.122.56804
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.1/System.Collections.Specialized.dll
----------------------------------------
Microsoft.Win32.Primitives
    程序集版本:7.0.0.0
    Win32 版本:7.0.122.56804
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.1/Microsoft.Win32.Primitives.dll
----------------------------------------
System.Threading
    程序集版本:7.0.0.0
    Win32 版本:7.0.122.56804
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.1/System.Threading.dll
----------------------------------------
System.Diagnostics.TraceSource
    程序集版本:7.0.0.0
    Win32 版本:7.0.122.56804
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.1/System.Diagnostics.TraceSource.dll
----------------------------------------
System.Collections
    程序集版本:7.0.0.0
    Win32 版本:7.0.122.56804
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.1/System.Collections.dll
----------------------------------------
System.Drawing.Common
    程序集版本:7.0.0.0
    Win32 版本:7.0.122.56804
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.1/System.Drawing.Common.dll
----------------------------------------
System.Collections.Concurrent
    程序集版本:7.0.0.0
    Win32 版本:7.0.122.56804
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.1/System.Collections.Concurrent.dll
----------------------------------------
System.ComponentModel.EventBasedAsync
    程序集版本:7.0.0.0
    Win32 版本:7.0.122.56804
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.1/System.ComponentModel.EventBasedAsync.dll
----------------------------------------
System.Threading.Thread
    程序集版本:7.0.0.0
    Win32 版本:7.0.122.56804
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.1/System.Threading.Thread.dll
----------------------------------------
Accessibility
    程序集版本:4.0.0.0
    Win32 版本:7.0.122.56811
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.1/Accessibility.dll
----------------------------------------
System.ComponentModel.TypeConverter
    程序集版本:7.0.0.0
    Win32 版本:7.0.122.56804
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.1/System.ComponentModel.TypeConverter.dll
----------------------------------------
System.Memory
    程序集版本:7.0.0.0
    Win32 版本:7.0.122.56804
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.1/System.Memory.dll
----------------------------------------
System.Numerics.Vectors
    程序集版本:7.0.0.0
    Win32 版本:7.0.122.56804
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.1/System.Numerics.Vectors.dll
----------------------------------------
System.Runtime.Loader
    程序集版本:7.0.0.0
    Win32 版本:7.0.122.56804
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.1/System.Runtime.Loader.dll
----------------------------------------
System.Windows.Forms.resources
    程序集版本:7.0.0.0
    Win32 版本:7.0.122.56811
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.1/zh-Hans/System.Windows.Forms.resources.dll
----------------------------------------
Microsoft.Win32.SystemEvents
    程序集版本:7.0.0.0
    Win32 版本:7.0.122.56804
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.1/Microsoft.Win32.SystemEvents.dll
----------------------------------------
System.Resources.Extensions
    程序集版本:7.0.0.0
    Win32 版本:7.0.122.56804
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.1/System.Resources.Extensions.dll
----------------------------------------
System.Drawing
    程序集版本:7.0.0.0
    Win32 版本:7.0.122.56811
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.1/System.Drawing.dll
----------------------------------------
System.ObjectModel
    程序集版本:7.0.0.0
    Win32 版本:7.0.122.56804
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.1/System.ObjectModel.dll
----------------------------------------
System.Collections.NonGeneric
    程序集版本:7.0.0.0
    Win32 版本:7.0.122.56804
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.1/System.Collections.NonGeneric.dll
----------------------------------------
System.Text.Json
    程序集版本:7.0.0.0
    Win32 版本:7.0.122.56804
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.1/System.Text.Json.dll
----------------------------------------
Microsoft.Win32.Registry
    程序集版本:7.0.0.0
    Win32 版本:7.0.122.56804
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.1/Microsoft.Win32.Registry.dll
----------------------------------------
System.ComponentModel
    程序集版本:7.0.0.0
    Win32 版本:7.0.122.56804
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.1/System.ComponentModel.dll
----------------------------------------
System.Linq.Parallel
    程序集版本:7.0.0.0
    Win32 版本:7.0.122.56804
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.1/System.Linq.Parallel.dll
----------------------------------------
Masuit.Tools.Abstractions
    程序集版本:2.5.7.7
    Win32 版本:不可用
    代码库:
----------------------------------------
SixLabors.ImageSharp
    程序集版本:2.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Net.Http
    程序集版本:7.0.0.0
    Win32 版本:7.0.122.56804
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.1/System.Net.Http.dll
----------------------------------------
Newtonsoft.Json
    程序集版本:13.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
netstandard
    程序集版本:2.1.0.0
    Win32 版本:7.0.122.56804
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.1/netstandard.dll
----------------------------------------
System.Linq.Expressions
    程序集版本:7.0.0.0
    Win32 版本:7.0.122.56804
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.1/System.Linq.Expressions.dll
----------------------------------------
System.Net.Primitives
    程序集版本:7.0.0.0
    Win32 版本:7.0.122.56804
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.1/System.Net.Primitives.dll
----------------------------------------
System.Security.Cryptography
    程序集版本:7.0.0.0
    Win32 版本:7.0.122.56804
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.1/System.Security.Cryptography.dll
----------------------------------------
System.Diagnostics.Tracing
    程序集版本:7.0.0.0
    Win32 版本:7.0.122.56804
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.1/System.Diagnostics.Tracing.dll
----------------------------------------
System.Diagnostics.DiagnosticSource
    程序集版本:7.0.0.0
    Win32 版本:7.0.122.56804
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.1/System.Diagnostics.DiagnosticSource.dll
----------------------------------------
System.Net.Security
    程序集版本:7.0.0.0
    Win32 版本:7.0.122.56804
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.1/System.Net.Security.dll
----------------------------------------
System.Linq
    程序集版本:7.0.0.0
    Win32 版本:7.0.122.56804
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.1/System.Linq.dll
----------------------------------------
System.Text.RegularExpressions
    程序集版本:7.0.0.0
    Win32 版本:7.0.122.56804
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.1/System.Text.RegularExpressions.dll
----------------------------------------
System.Threading.ThreadPool
    程序集版本:7.0.0.0
    Win32 版本:7.0.122.56804
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.1/System.Threading.ThreadPool.dll
----------------------------------------
System.Private.Uri
    程序集版本:7.0.0.0
    Win32 版本:7.0.122.56804
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.1/System.Private.Uri.dll
----------------------------------------
System.Diagnostics.StackTrace
    程序集版本:7.0.0.0
    Win32 版本:7.0.122.56804
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.1/System.Diagnostics.StackTrace.dll
----------------------------------------
System.Reflection.Metadata
    程序集版本:7.0.0.0
    Win32 版本:7.0.122.56804
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.1/System.Reflection.Metadata.dll
----------------------------------------
System.Collections.Immutable
    程序集版本:7.0.0.0
    Win32 版本:7.0.122.56804
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.1/System.Collections.Immutable.dll
----------------------------------------
System.Diagnostics.FileVersionInfo
    程序集版本:7.0.0.0
    Win32 版本:7.0.122.56804
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.1/System.Diagnostics.FileVersionInfo.dll
----------------------------------------

************** JIT 调试 **************

**Comment by deYangar** [comment]
出现异常，点继续，然后点更新索引，再报错，异常文本后面两行会出现些微变化

************** 异常文本 **************
System.IO.IOException: 系统无法打开文件。 : 'X:\3D_二次元\【图集】【萝】ぁぁぁぁ\2018-05-19 16-3720180519配信ラクガキ'
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateRelativeDirectoryHandle(ReadOnlySpan`1 relativePath, String fullPath)
   at System.IO.Enumeration.FileSystemEnumerator`1.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToList()
   at 以图搜图.Form1.btnIndex_Click(Object sender, EventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   ****at InvokeStub_SendOrPostCallback.Invoke(Object, Object, IntPtr*)****
   ****at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)****

**Comment by ldqk** [comment]
看起来像是文件系统权限问题，要不你自己跑源代码调试看看

**Comment by deYangar** [comment]
跑了一下源代码，顺便观察了一下。发现在报错异常的时候，挂载的网络驱动器全部卡住打不开（我要索引的文件夹是局域网内的nas映射的网络驱动器）。在异常之前，以及一旦把异常关了，网络驱动器没有任何问题
![QQ截图20221230202939](https://user-images.githubusercontent.com/70438628/210070637-26b5380b-d644-4c28-babd-690e5acd9528.jpg)
![QQ截图20221230202952](https://user-images.githubusercontent.com/70438628/210070641-3bba1a84-352d-4b0f-8650-b918c8d482a3.jpg)

**Comment by ldqk** [comment]
你还是跑本地文件吧，不然你自己调好了提pr吧

**Comment by deYangar** [comment]
ok
