### ISSUE TITLE
is:issue is:open 这个1.5版本点击选择文件夹或者文件就无反应，软件崩溃，希望能解决，也希望后面能增加图片拖拽到窗口直接生成路径，还有可以粘贴剪切板里面的图片。大佬牛逼

### ISSUE THREAD

**Issue by SeamusCheng** [ldqk/ImageSearch#12]
is:issue is:open 这个1.5版本点击选择文件夹或者文件就无反应，软件崩溃，希望能解决，也希望后面能增加图片拖拽到窗口直接生成路径，还有可以粘贴剪切板里面的图片。大佬牛逼

**Comment by ldqk** [comment]
demo级项目，能用就行

**Comment by daowaidao** [comment]
请问，选择文件夹就卡死了，手动复制文件夹地址，更新索引后就弹出错误了，怎么解决？

**Comment by ldqk** [comment]
> 请问，选择文件夹就卡死了，手动复制文件夹地址，更新索引后就弹出错误了，怎么解决？

上传下错误日志看看

**Comment by daowaidao** [comment]
额，在你博客下载的，就一个exe,出错了也没有生成错误日志

**Comment by ldqk** [comment]
已解决
