### ISSUE TITLE
我想选择硬盘根目录时候提示错误

### ISSUE THREAD

**Issue by kangkang623** [ldqk/ImageSearch#18]
只能选择下级文件夹，另外请问缓存的索引文件夹放在哪里，硬盘小，内存都没了。可以添加单独的索引文件出来吗，这样就可以转移exe文件了。最后非常感谢作者的软件，使用效果非常好，如果能做的功能更多一下，付费版也可以良性循环

**Comment by ldqk** [comment]
索引文件在程序同目录下，index.json文件
