### ISSUE TITLE
感谢作者开发这样的软件！可以进一步优化吗？

### ISSUE THREAD

**Issue by Spacesky2022** [ldqk/ImageSearch#20]
感谢作者开发这样的软件！太喜欢了！图片比较多，用这个在本地搜索太棒了！可以进一步优化吗？

如果能全屏就好了，这样可以更仔细地查看搜索图和被搜索图之间的区别 

其实还可以更加完善 比如增加个放大镜功能 看看两张图片的区别。

您可以放个打赏二维码，多少是个心意，我希望这个软件可以一直更新下去。再次感谢！

**Comment by ldqk** [comment]
这个软件更多的目的是demo图像对比和搜索算法，我不擅长于UI设计，如果有愿意帮忙优化UI的伙伴可以提PR
