### ISSUE TITLE
有个疑问 使用以图搜图的时候  图片名称的问题

### ISSUE THREAD

**Issue by 777sfdf** [ldqk/ImageSearch#22]
有个疑问 使用以图搜图的时候  最开始我在文件夹内 把一张图片复制出来一个副本  但是后来我又给其改成其他名字  之后就出现 在检索的过程中 该文件的名称还是某某副本的名字 即使我已经重新清理然后编译 还是这样的问题 该怎么解决呢 谢谢!
如下图所示这是检索出来的内容
![image](https://github.com/ldqk/ImageSearch/assets/118660349/cb66b9fe-a8ff-4532-bbb4-f7b36a3da107)

而实际文件夹中的内容是下边这样的
![image](https://github.com/ldqk/ImageSearch/assets/118660349/ff42deb6-e513-4b7e-b7bb-5b85ac72c123)

**Comment by ldqk** [comment]
重建一下索引就好了

**Comment by 777sfdf** [comment]
好的 感谢  我把移除无效索引勾选上后 然后再点击更新索引就好了
