### ISSUE TITLE
会提供图片查重功能吗？

### ISSUE THREAD

**Issue by Youxikong** [ldqk/ImageSearch#24]
如题，希望能对索引的文件进行查重。

**Comment by ldqk** [comment]
图片查重你可以直接使用[DuplicateCleaner](https://masuit.org/1776)这个软件，这个软件功能强大，但是DuplicateCleaner没有提供搜图功能，所以[ImageSearch](https://github.com/ldqk/ImageSearch)可以和DuplicateCleaner作为相互的补充使用

**Comment by Youxikong** [comment]
谢谢，我去试试。
