### ISSUE TITLE
请求加入删除图片的功能

### ISSUE THREAD

**Issue by walkonbothsides** [ldqk/ImageSearch#25]
作者的项目很给力，找相似图片特别快，想用来删除一些相似的图片而不只是列出列表

**Comment by ldqk** [comment]
你想找的可能是：[DuplicateCleaner](https://masuit.org/1776)

**Comment by walkonbothsides** [comment]
有使用过[DuplicateCleaner](https://masuit.org/1776)，但是感觉没这个简单无脑

**Comment by ldqk** [comment]
[DuplicateCleaner](https://masuit.org/1776)没有搜图功能，这个小工具也只是为了弥补[DuplicateCleaner](https://masuit.org/1776)的功能，没必要再创造一个一样的工具😂😂

**Comment by walkonbothsides** [comment]
好吧，谢谢解答
