### ISSUE TITLE
必须给个大大的赞！希望能增加自动扫描功能

### ISSUE THREAD

**Issue by inzens** [ldqk/ImageSearch#28]
软件炒鸡好用，已经成为你的忠粉了~搜索快、准、狠！！！

作为一个忠实用户，用了半年多，感觉唯一的欠缺点就是自动扫描的功能，比如可以设置自动扫描那个路径、什么时候自动扫描。

有这个功能就是咱心目中最完美的工具了，不过目前来看也是相当完美的！

**Comment by ldqk** [comment]
自动扫描实现不了，如果要做，则只能做成全盘扫描，这样效率太低了，而且建索引的时候是非常吃CPU的，自动扫描就意味着文件随时在发生变化，就随时在做全盘扫描建索引，非常影响其他进程
