### ISSUE TITLE
JPG或JPEG的图片是无法识别，截图无法搜索

### ISSUE THREAD

**Issue by haiyuanbo** [ldqk/ImageSearch#31]
大神，您好，您的本地以图搜图很实用，速度也很快，但有两个问题可能需要改进下：1. JPG或JPEG的图片是无法识别的，无法做索引，需要把图片全部转为PNG格式才可以，比较麻烦。2. 截图后也无法从剪切板中搜索，这两个问题需要修复下，另外再增加一个功能，截图后，在软件界面按键盘的ctrl+v就能本地搜图（这里无需按确定就能搜索）就完美了，希望作者大神能改进下，感谢！！然后作者大神可以在软件设置一个捐赠功能，大家觉得好用会捐赠的

**Comment by ldqk** [comment]
你说的这两种情况是不能存在的，不知道你用的是不是最新版，JPG或JPEG的图片不能识别不知道你的图片的真实格式是否是jpg？或者是文件访问权限的问题？剪切板搜索也是支持直接CTRL+V的

**Comment by haiyuanbo** [comment]
用的是上面截图的1.16版本，确实是用不了jpg图片的，JPG图片不支持添加索引，截图什么都没显示的，即便是转后的PNG导入索引，打开已经有的图片截图搜索也是什么都没显示的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ldqk/ImageSearch"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月7日(星期天) 上午9:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ldqk/ImageSearch] JPG或JPEG的图片是无法识别，截图无法搜索 (Issue #31)





 
你说的这两种情况是不能存在的，不知道你用的是不是最新版，JPG或JPEG的图片不能识别不知道你的图片的真实格式是否是jpg？或者是文件访问权限的问题？剪切板搜索也是支持直接CTRL+V的

**Comment by ldqk** [comment]
能否提供几张不能识别的jpg图发我调试看看？

**Comment by aileng114** [comment]
> 能否提供几张不能识别的jpg图发我调试看看？

您好，没有exe文件请问如何运行？

**Comment by ldqk** [comment]
> > 能否提供几张不能识别的jpg图发我调试看看？
> 
> 您好，没有exe文件请问如何运行？

exe文件在release页下载

**Comment by haiyuanbo** [comment]
> 能否提供几张不能识别的jpg图发我调试看看？

JPG图片发过去了，有测试出问题吗？

**Comment by ldqk** [comment]
> > 能否提供几张不能识别的jpg图发我调试看看？
> 
> JPG图片发过去了，有测试出问题吗？

在哪儿？

**Comment by haiyuanbo** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ldqk/ImageSearch"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月9日(星期四) 上午8:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ldqk/ImageSearch] JPG或JPEG的图片是无法识别，截图无法搜索 (Issue #31)





   
能否提供几张不能识别的jpg图发我调试看看？
  
JPG图片发过去了，有测试出问题吗？
  
在哪儿？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;


从QQ邮箱发来的超大附件

JPG图片测试.rar (5.62M, 无限期)进入下载页面：https://mail.qq.com/cgi-bin/ftnExs_download?k=71396433ce32c3c6f899b903433757164d4d000406000408185851515d1a030a560f490054535714050052505601070e515b530665386573657ea98fa39bd7dbffed4a4104456504&t=exs_ftn_download&code=59d3e7e9

**Comment by haiyuanbo** [comment]
> > > 能否提供几张不能识别的jpg图发我调试看看？
> > 
> > 
> > JPG图片发过去了，有测试出问题吗？
> 
> 在哪儿？

发在上面了，能下载吗

**Comment by ldqk** [comment]
已修正，下载最新版即可

**Comment by haiyuanbo** [comment]
之前加了好多索引图片，请问怎么套用之前的索引？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ldqk/ImageSearch"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月9日(星期四) 上午9:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ldqk/ImageSearch] JPG或JPEG的图片是无法识别，截图无法搜索 (Issue #31)





 
已修正，下载最新版即可

**Comment by ldqk** [comment]
索引文件在exe同目录下，两个json文件就是索引文件
