### ISSUE TITLE
更新索引时，软件直接闪退，没有任何信息

### ISSUE THREAD

**Issue by big-dream** [ldqk/ImageSearch#33]
初次使用，选择文件夹，然后点击更新索引按钮，快更新完时，软件卡住，然后自动关闭了。
没有弹出任何信息，在exe所在目录没有找到相关日志信息，所以不知道问题出在哪里。

-- 软件版本 --
ImageSearch_win_x64_1.16
-- 系统信息 --
版本	Windows 11 专业教育版
版本	23H2
安装日期	‎2022-‎9-‎26
操作系统版本	22631.3447
体验	Windows Feature Experience Pack 1000.22688.1000.0

![image](https://github.com/ldqk/ImageSearch/assets/9215157/f6c17e69-7a8b-4a42-a4fb-772e04b64d72)

**Comment by ldqk** [comment]
多试一下看看？

**Comment by ldqk** [comment]
可能是你系统问题吧，换个电脑看看？
