### ISSUE TITLE
希望查找结果里可以按f2来复制图片文件名或者重命名图片文件名

### ISSUE THREAD

**Issue by coccvo** [ldqk/ImageSearch#34]
希望查找结果里可以按f2来复制图片文件名或者重命名图片文件名

**Comment by ldqk** [comment]
本应用是一个搜索工具，不考虑增加文件管理的相关功能，搜索列表是可以按ctrl c复制文件路径的，你也可以双击调用系统默认的图片浏览器打开对应文件，在图片浏览器中重命名，也可以右键在系统默认的资源管理器中打开文件位置，进行重命名操作
