### ISSUE TITLE
在查找结果中无法删除指定图片

### ISSUE THREAD

**Issue by BoHeZi** [ldqk/ImageSearch#35]
提示：除非 DataGridView 被数据绑定到支持更改通知并允许删除的 IBindingList，否则不能以编程方式移除行。

**Comment by ldqk** [comment]
是最新版本的吗

**Comment by BoHeZi** [comment]
> 这是最新版本吗

是的

**Comment by BoHeZi** [comment]
第一次搜索里删除成功了，之后再搜索、重启，都无法删除

**Comment by ldqk** [comment]
已更新

**Comment by BoHeZi** [comment]
测试了一下新版，如果全选所有路径删除的话，提示：未能找到名为 路径 的列。（Parameter 'columnName'）
![image](https://github.com/user-attachments/assets/2d874f19-0a72-4577-8282-5e867da7558e)

**Comment by ldqk** [comment]
已更新

**Comment by BoHeZi** [comment]
![@T@F9@AL5XVQ_%WQJAL{2KK](https://github.com/user-attachments/assets/424a1ade-059e-42f7-b7da-a5be17d44501)经测试没有问题了，大佬修复好快
