### ISSUE TITLE
更新索引失败,

### ISSUE THREAD

**Issue by xclsky1** [ldqk/ImageSearch#36]
更新索引失败,
![image](https://github.com/user-attachments/assets/32137b17-731a-4f1c-89f8-f4b0fc10584c)

**Comment by xclsky1** [comment]
用的是 SMB 映射 盘符

**Comment by ldqk** [comment]
有安装everything吗？

**Comment by ldqk** [comment]
那要确保everything有索引你的目录才行

**Comment by ldqk** [comment]
AI吃算例啊

**Comment by xclsky1** [comment]
![image](https://github.com/user-attachments/assets/246e962b-99ab-4960-b5e8-f0d4a42f4da0)
相似度最底只能到70 还能再设底点嘛  都刷不出图片

**Comment by ldqk** [comment]
相似度低于70已经是肉眼看上去完全不一样的图片了

**Comment by xclsky1** [comment]
![image](https://github.com/user-attachments/assets/2ecf85ff-8924-477e-ab11-5ac0dd8aed93)
这玩意不行啊...直接目录下 截图都识别不出来.

**Comment by ldqk** [comment]
截图没截全吧，如果只截取的其中部分区域是搜索不到的

**Comment by xclsky1** [comment]
呃..如果我都有全图....那还有搜的必要嘛...

**Comment by ldqk** [comment]
这个搜索的目的主要是为了在海量图片中找到相似图片/重复图片，并文件定位，方便管理
