### ISSUE TITLE
线程间操作无效: 从不是创建控件“cbRemoveInvalidIndex”的线程访问它

### ISSUE THREAD

**Issue by tangxiaoqi-tangxiao** [ldqk/ImageSearch#5]
![微信截图_20220909143033](https://user-images.githubusercontent.com/54069236/190540188-bbd67002-7c24-40ff-9af1-a9672cce2e9c.png)

**Comment by tangxiaoqi-tangxiao** [comment]
一个跨线程访问控件的错误

**Comment by ldqk** [comment]
已修正
